spring.application.name=eventsapp
spring.datasource.url=jdbc:mysql://localhost:3306/eventsapp
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=3f1b8c71b42e4efa89c6f7b673e63412c421cff4b449b6f3d0df35c5e7de1b8c
app.jwt.expiration=3600000
app.jwt.issuer=eventsapp
