# =======================
# Server
# EB sets PORT=5000; locally this will keep 5000 unless you override.
server.port=${PORT:8080}

# =======================
# DataSource (MySQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql:///ordersapp?cloudSqlInstance=lunara-488522:us-central1:ordersdb&socketFactory=com.google.cloud.sql.mysql.SocketFactory&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:S&o2015.2022}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.open-in-view=false

# =======================
# Hikari (connection pool)
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:10}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN:2}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000